[profile.default]
src = "contracts"
out = "out"
libs = ["lib", "node_modules"]
test = "test"
cache_path = "cache_foundry"
solc_version = "0.8.27"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
fs_permissions = [{ access = "read-write", path = "./" }]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
fuji = "https://api.avax-test.network/ext/bc/C/rpc"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
